@echo off
cd /d "%~dp0"
echo Staging complete-ERP files...
git add "admin\ap_ar_aging.php"
git add "admin\approvals.php"
git add "admin\bank_accounts.php"
git add "admin\batches.php"
git add "admin\chart_of_accounts.php"
git add "admin\credit_notes.php"
git add "admin\customer_360.php"
git add "admin\debit_notes.php"
git add "admin\documents.php"
git add "admin\erp_reports_center.php"
git add "admin\financial_periods.php"
git add "admin\financial_statements.php"
git add "admin\fulfilment.php"
git add "admin\general_ledger.php"
git add "admin\gst_summary.php"
git add "admin\journals.php"
git add "admin\notifications.php"
git add "admin\print_erp.php"
git add "admin\quality_checks.php"
git add "admin\rfqs.php"
git add "admin\sales_channels.php"
git add "admin\shipments.php"
git add "admin\stock_counts.php"
git add "admin\stock_transfers.php"
git add "admin\supplier_360.php"
git add "admin\transaction_trace.php"
git add "admin\warehouse_locations.php"
git add "admin\warehouse_stock.php"
git add "assets\db_query\admin\accounting_api.php"
git add "assets\db_query\admin\accounting_engine.php"
git add "assets\db_query\admin\approvals_api.php"
git add "assets\db_query\admin\erp_ext.php"
git add "assets\db_query\admin\notifications_api.php"
git add "assets\db_query\admin\procurement_api.php"
git add "assets\db_query\admin\sales_ext_api.php"
git add "assets\db_query\admin\warehouse_api.php"
git add "erp_complete_migration.sql"
git add "erp_complete_rollback.sql"
git add "erp_complete_verify.sql"
git add "admin\assets\erp.js"
git add "admin\expenses.php"
git add "admin\goods_receipts.php"
git add "admin\includes\sidebar.php"
git add "admin\index.php"
git add "admin\profit_loss.php"
git add "admin\purchase_orders.php"
git add "admin\purchase_requests.php"
git add "admin\purchase_returns.php"
git add "assets\db_query\admin\costing_engine.php"
git add "assets\db_query\admin\erp_docs.php"
git add "assets\db_query\admin\erp_report_lib.php"
git add "assets\db_query\admin\erp_reports.php"
git add "assets\db_query\admin\inventory_ops_api.php"
git add "assets\db_query\admin\purchase_api.php"
git add "purchase_request_approval_workflow.sql"
git add "assets\db_query\admin\erp_helper.php"
git add "admin\includes\check_admin.php"
git add "Claude outputs\valluvam_complete_erp_audit_and_gap_analysis.md"
git add "Claude outputs\valluvam_complete_erp_implementation_report.md"
git add "deploy_complete_erp.bat"
echo.
echo Committing...
git commit -m "Admin: complete ERP layer (approvals, notifications, documents v2, RFQ/QC/transport, warehouse sub-ledger, double-entry accounting, sales ext) + merge with Manager-Backend PR approval"
echo.
echo Pushing...
git push
echo.
echo Done. Press any key to close this window.
pause
